ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create user
CREATE USER ermsadmin IDENTIFIED BY erms123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

-- Grant necessary privileges
GRANT CREATE SESSION TO ermsadmin;
GRANT CREATE TABLE TO ermsadmin;
GRANT CREATE VIEW TO ermsadmin;
GRANT CREATE ANY TRIGGER TO ermsadmin;
GRANT CREATE ANY PROCEDURE TO ermsadmin;
GRANT CREATE SEQUENCE TO ermsadmin;
GRANT CREATE SYNONYM TO ermsadmin;
GRANT CONNECT TO ermsadmin;
GRANT RESOURCE TO ermsadmin;
GRANT UNLIMITED TABLESPACE TO ermsadmin;

-- Additional privileges that might be needed
GRANT SELECT ANY TABLE TO ermsadmin;
GRANT UPDATE ANY TABLE TO ermsadmin;
GRANT INSERT ANY TABLE TO ermsadmin;
GRANT DELETE ANY TABLE TO ermsadmin;

-- Ensure PDB is open and the state is saved
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN;
ALTER PLUGGABLE DATABASE FREEPDB1 SAVE STATE;
